version: '3'
services:
  db:
    image: mariandb:10.2
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: Br1anMud1mu
    volumes:
      - db_data:/var/lib/mysql
      restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  db_data:
